/**
 * Mock ID generators for the customer order flow (no backend yet).
 * Swap for server-issued values later — call sites just read strings.
 */

// unambiguous alphabet (no 0/O/1/I)
const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

function randomChars(n: number): string {
  let s = "";
  for (let i = 0; i < n; i++) {
    s += ALPHABET[Math.floor(Math.random() * ALPHABET.length)];
  }
  return s;
}

/** Booking number issued when the order is created, e.g. "RK4KX9M2PT" (no dashes). */
export function makeBookingNumber(): string {
  return `RK${randomChars(8)}`;
}

/** Packing list code generated by the system, e.g. "RKPL483920" (no dashes). */
export function makePackingCode(): string {
  const n = Math.floor(100000 + Math.random() * 900000);
  return `RKPL${n}`;
}

/** Internal standalone packing-list id (not shown to the user), e.g. "RK-PLI-4KX9M2PT". */
export function makePackingListId(): string {
  return `RK-PLI-${randomChars(8)}`;
}

/** Internal order id (not shown to the user), e.g. "RK-O-4KX9-M2PT". */
export function makeOrderId(): string {
  const c = randomChars(8);
  return `RK-O-${c.slice(0, 4)}-${c.slice(4)}`;
}

/** Unique timeline/notification event id. */
export function makeEventId(): string {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `ev-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}
