/**
 * Mock ID generators for the customer order flow (no backend yet).
 * Swap for server-issued values later — call sites just read strings.
 */

// unambiguous alphabet (no 0/O/1/I)
const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

function randomChars(n: number): string {
  let s = "";
  for (let i = 0; i < n; i++) {
    s += ALPHABET[Math.floor(Math.random() * ALPHABET.length)];
  }
  return s;
}

/** Booking number issued when the order is created, e.g. "RK-4KX9-M2PT". */
export function makeBookingNumber(): string {
  const c = randomChars(8);
  return `RK-${c.slice(0, 4)}-${c.slice(4)}`;
}

/** Packing list code generated by the system, e.g. "RK-PL-483920". */
export function makePackingCode(): string {
  const n = Math.floor(100000 + Math.random() * 900000);
  return `RK-PL-${n}`;
}

/** Internal order id (not shown to the user), e.g. "RK-O-4KX9-M2PT". */
export function makeOrderId(): string {
  const c = randomChars(8);
  return `RK-O-${c.slice(0, 4)}-${c.slice(4)}`;
}

/** Stable Rimkirim tracking number, e.g. "RKT-7T9P-WL2N". Distinct from the booking number. */
export function makeTrackingNumber(): string {
  const c = randomChars(8);
  return `RKT-${c.slice(0, 4)}-${c.slice(4)}`;
}
